<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .company { font-size: 20px; font-weight: bold; color: #1a56db; }
        .invoice-title { font-size: 28px; font-weight: bold; color: #374151; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
        .section-label { font-size: 10px; text-transform: uppercase; color: #6b7280; margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #1a56db; color: white; padding: 10px; text-align: left; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; }
        .totals { text-align: right; }
        .total-row td { font-weight: bold; font-size: 14px; }
        .status-badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 11px; font-weight: bold; }
        .status-paid { background: #d1fae5; color: #065f46; }
        .status-sent { background: #dbeafe; color: #1e40af; }
        .status-overdue { background: #fee2e2; color: #991b1b; }
        .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="company">Flovig</div>
            <div>Integrated Project & Marketing Management</div>
        </div>
        <div style="text-align:right">
            <div class="invoice-title">INVOICE</div>
            <div>{{ $invoice->invoice_number }}</div>
            <div>
                <span class="status-badge status-{{ $invoice->status }}">
                    {{ strtoupper($invoice->status) }}
                </span>
            </div>
        </div>
    </div>

    <div class="info-grid">
        <div>
            <div class="section-label">Bill To</div>
            <strong>{{ $invoice->client->name }}</strong><br>
            {{ $invoice->client->email }}
        </div>
        <div style="text-align:right">
            <div class="section-label">Invoice Details</div>
            <strong>Project:</strong> {{ $invoice->project->name }}<br>
            <strong>Issue Date:</strong> {{ $invoice->issue_date->format('d M Y') }}<br>
            <strong>Due Date:</strong> {{ $invoice->due_date->format('d M Y') }}<br>
            @if($invoice->paid_at)
            <strong>Paid At:</strong> {{ $invoice->paid_at->format('d M Y') }}<br>
            @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align:center">Qty</th>
                <th style="text-align:right">Unit Price</th>
                <th style="text-align:right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoice->items as $item)
            <tr>
                <td>{{ $item->description }}</td>
                <td style="text-align:center">{{ $item->quantity }}</td>
                <td style="text-align:right">Rp {{ number_format($item->unit_price, 0, ',', '.') }}</td>
                <td style="text-align:right">Rp {{ number_format($item->total, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="totals">
        <table style="width:300px;float:right;">
            <tr>
                <td>Subtotal</td>
                <td style="text-align:right">Rp {{ number_format($invoice->subtotal, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td>Tax ({{ $invoice->tax }}%)</td>
                <td style="text-align:right">Rp {{ number_format($invoice->total - $invoice->subtotal, 0, ',', '.') }}</td>
            </tr>
            <tr class="total-row" style="background:#f3f4f6">
                <td>TOTAL</td>
                <td style="text-align:right">Rp {{ number_format($invoice->total, 0, ',', '.') }}</td>
            </tr>
        </table>
        <div style="clear:both"></div>
    </div>

    @if($invoice->notes)
    <div style="margin-top:20px;padding:15px;background:#f9fafb;border-radius:8px;">
        <strong>Notes:</strong><br>
        {{ $invoice->notes }}
    </div>
    @endif

    <div class="footer">
        Generated by Flovig &mdash; {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
